# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_p0TFxympl_tK9bsaDL_cB3sHOMIA2MH
"""

!pip install -q gradio
!pip install -q git+https://github.com/huggingface/transformers.git

import gradio as gr
import numpy as np
import joblib

# Load the trained regressor model
regressor = joblib.load("/content/decision_tree_model.pkl")  # Replace with the actual path

def predict_new_data(N, P, K, temperature, humidity, ph, durationmonths, rainfall, period):
    input_data = np.array([[N, P, K, temperature, humidity, ph, durationmonths, rainfall, period]])
    predictedCrop = regressor.predict(input_data)
    return predictedCrop[0]

iface = gr.Interface(
    fn=predict_new_data,
    inputs=[
        gr.inputs.Number(label="N"),
        gr.inputs.Number(label="P"),
        gr.inputs.Number(label="K"),
        gr.inputs.Number(label="Temperature"),
        gr.inputs.Number(label="Humidity"),
        gr.inputs.Number(label="pH"),
        gr.inputs.Number(label="Duration in Months"),
        gr.inputs.Number(label="Rainfall"),
        gr.inputs.Radio(["0","1","2"], label="Period"),
    ],
    outputs=gr.outputs.Textbox(label="AgriGenie - Predicted Crop"),
    title="Crop Prediction Site",
    description="Predicting the crop for New Age Farmers.",
)

iface.launch(debug=True,share=True)

